export const TOKEN ='TOKEN'
export const ISCOLLAPSE = 'ISCOLLAPSE'



export const FIGHTFIRSTNUM = 'FIGHTFIRSTNUM'
export const FIGHTFIRSTBNUM = 'FIGHTFIRSTBNUM'
export const FIGHTSECONDNUM = 'FIGHTSECONDNUM'
export const FIGHTTHIRDNUM = 'FIGHTTHIRDNUM'
export const FIGHTFOURTHNUM = 'FIGHTFOURTHNUM'

